version: "3.7"
services:
  php7.2:
    image: magonxesp/php:7.2
    ports: 
      - 80:8000
    volumes:
      - ./:/var/www/html
  mysql:
    image: mysql/mysql-server:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'