version: "3.7"
services:
  php7.2:
    image: magonx/php:7.2
    ports: 
      - 8000:80
    volumes:
      - ./:/var/www/html
    links:
      - mysql
    depends_on:
      - mysql

  mysql:
    image: mysql/mysql-server:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: 'drupal'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'root'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'root'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'root'
